version: '2.2'
services:
  bloggen_api:
    # The name will be displayed # in docker ps
    container_name: bloggen_api
    # Build the image from Dockerfile
    ports:
      - "7000:7000"
    build:
      context: .
      dockerfile: Dockerfile
    image: loup21991/bloggen:latest
    env_file:
      - .env
